### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by HoraceDiesel** [lwhiteley/react-push-menu#11]
tried `yarn add react-push-menu` and failed with the postinstall script: 
```
node_modules/react-push-menu: Command failed.
Exit code: 127
Command: install-peers -f && cd example && npm i
Arguments:
```

then tried with npm, `npm install react-push-menu`, got a bit insights: 
```
npm ERR! react-push-menu@3.0.1 postinstall: `install-peers -f && cd example && npm i`
npm ERR! Exit status 1
```
`sh: line 0: cd: example: No such file or directory`

Why the example directory does not exit? And why do you force user to install the example app?

**Comment by lwhiteley** [comment]
sorry seems to be an oversight. ill fix it right away

**Comment by lwhiteley** [comment]
version 3.0.2 released to npm
