### ISSUE TITLE
TypeError: Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by gabriel216** [lwhiteley/react-push-menu#2]
> 197 |   propMap: _react.PropTypes.object,

**Comment by lwhiteley** [comment]
i believe this is due to react migrating proptypes to its own package. ill push a fix shortly

**Comment by lwhiteley** [comment]
react-push-menu@0.1.0 is in npm, let me know if it resolves your issue so i can close.

please note: `proptypes` is now a peer dependency

**Comment by gabriel216** [comment]
how import proptypes?

**Comment by lwhiteley** [comment]
run `npm i --save proptypes` for your main project

**Comment by gabriel216** [comment]
TypeError: Cannot read property 'children' of undefined
 153 | var _this2 = this;
  154 | 
  155 | var propMap = Object.assign({}, defaultPropMaps, this.props.propMap);
> 156 | var nodeChildren = this.props.nodes[propMap.childPropName];
  157 | return _react2.default.createElement(
  158 |   'div',
  159 |   { className: 'rpm-container', id: 'rpm-container' },

**Comment by lwhiteley** [comment]
that's an error i can prevent from happening but are you looking at the docs and example:

https://github.com/lwhiteley/react-push-menu/blob/master/example/index.js

if you dont define the menu data then you will get that `undefined` error

**Comment by gabriel216** [comment]
Could you help me implement it? since I have a Navbar component and a separate sideNav component
