### ISSUE TITLE
body  scroll issue

### ISSUE THREAD

**Issue by sunitakarle23** [lwhiteley/react-push-menu#3]
Hi,
I have used react-push-menu package in my react project for mobile menu's. I am getting scrolling issue when I scroll on menu the body getting scrolled. I tried to get an event when menu's opened to apply css to handle this issue but couldn't get any event or couldn't apply any custom event also.  Please help me to solve this. 

Thank's.

**Comment by lwhiteley** [comment]
let me check this out for you

**Comment by lwhiteley** [comment]
see PR #4
