### ISSUE TITLE
On starting: property 'string' of undefined

### ISSUE THREAD

**Issue by gucomecan** [lwhiteley/react-push-menu#6]
Hi, 
What I do:
[react-icons v2.2.1]
`yarn add react react-dom react-icons@2.2.1 --save` (it doesn't work with newest version - they change icons loading, now they are in one file /index.js/!)
`yarn add react-push-menu --save`
After that I include everything the doc describe, but when add
`import PushMenu from 'react-push-menu';` 
in one of my components the project return:
`index.js:44 Uncaught TypeError: Cannot read property 'string' of undefined` in the console!

index.js:44:
`IconBase.propTypes = {
  color: _react.PropTypes.string,
  size: _react.PropTypes.oneOfType([_react.PropTypes.string, _react.PropTypes.number]),
  style: _react.PropTypes.object
};`

[react-icons v3+] You should edit
in: build/DefaultBackButton `"require('react-icons/lib/fa/chevron-left');" --> require('react-icons/lib/fa');`
in: build/index.js  `require('react-icons/lib/fa/chevron-right'); --> require('react-icons/lib/fa');`
It is describe in [react-icons doc](https://www.npmjs.com/package/react-icons#migrate-from-version-2---3)

Thank's.

**Comment by lwhiteley** [comment]
version 1.0.0 has been released

react-icons has been removed as a peer dependency.

`expanderComponent` is now required

and a new optional prop `backIcon` is available for use

see [example](/example/index.js)

**Comment by gucomecan** [comment]
Hi, please update the Doc. Everyone should know what was changed.
