### ISSUE TITLE
error: when i changed propMap childPropName as customPropName 

### ISSUE THREAD

**Issue by nrsdnitin** [lwhiteley/react-push-menu#9]
` mlpushmenu.js:155 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at eval (mlpushmenu.js:155)
    at Array.forEach (<anonymous>)
    at mlPushMenu._initEvents (mlpushmenu.js:151)
    at mlPushMenu._init (mlpushmenu.js:118)
    at new mlPushMenu (mlpushmenu.js:79)
    at PushMenu.componentDidMount (index.js:147)
    at commitLifeCycles (react-dom.development.js:22101)
    at commitLayoutEffects (react-dom.development.js:25344)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385) `

 

data: 
`    const a = {
      header: 'All Categories',
      childrenCate: [
        {
          name: 'About',
          id: 1,
          link: '/about',
          childrenCate: [
            {name: 'Mission', id: 11, link: null, childrenCate: []},
            {name: 'Objectives', id: 12, link: null, childrenCate: []},
            {
              name: 'Goals',
              id: 13,
              link:
                '/about/goals',
              childrenCate: [
                {name: 'Charity', id: 131, link: null, childrenCate: []},
                {name: 'Clean Environment Plan', id: 132, link: null, childrenCate: []},
              ]
            }
          ]
        },
        {name: 'Services', id: 2, link: '/services', childrenCate: []},
        {name: 'People', id: 3, link: '/people', childrenCate: []},
        {name: 'Careers', id: 4, link: '/careers', childrenCate: []},
        {name: 'Contact', id: 5, link: null, childrenCate: []},
      ]
    }`

`        <PushMenu
          backIcon={<FaChevronLeft />}
          expanderComponent={FaChevronRight}
          onNodeClick={(e, {menu, node}) => {
            console.log(node)
            menu.tools.reset();
          }}
          //linkComponent={LinkComponent}
          isOpen={true}
          nodes={ a }
          type={'overlap'}
          propMap={{
            displayName: 'name',
            linkClasses: 'classes',
            expanderClasses: 'expClasses',
            childPropName: 'childrenCate',
            url: 'link'}}>
          <div className="rpm-trigger" id="rpm-trigger" >
            <FaBars />
          </div>
        </PushMenu>`

**Comment by lwhiteley** [comment]
Im actually doing a rewrite of the library and wont be supporting v1 anymore.

If you can submit a PR with a fix for this, i'd be happy to review and merge this if this fixes your problem faster
